name: flet_ads
description: Display Google Ads in Flet apps.
homepage: https://flet.dev
repository: https://github.com/flet-dev/flet-ads/src/flutter/flet_ads
issue_tracker: https://github.com/flet-dev/flet-ads/issues
version: 0.2.0
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  google_mobile_ads: ^6.0.0

  # flet: 0.70.0
  flet:
    git:
      url: https://github.com/flet-dev/flet.git
      path: packages/flet
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0